# Required: Home Assistant integration (MQTT discovery)
homeassistant: false

# Required: allow new devices to join.
# WARNING: Disable this after all devices have been paired!
permit_join: true

# Required: MQTT settings
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://sandbox.rightech.io'
 #user: '<ric-mqtt-username>'
 #password: '<ric-mqtt-password>'
  client_id: '<ric-mqtt-client-id>'


# Required: serial settings
serial:
  # Required: location of CC2531 USB sniffer
  port: /dev/ttyACM0
